### ISSUE TITLE
Cache Server 6.3.0 exits silently when trying to run from previous "cache_ram" data

### ISSUE THREAD

**Issue by LaserCannon** [Unity-Technologies/unity-cache-server#140]
I'm running into an issue where our ram_cache cache server crashes after about a week or two, and when turning it back on, it immediately quits with no message (log level 4). The only way to start it back up is to destroy the cache files, which is troublesome when it takes a lot of time to fill up our cache for our 5 different platforms.

The one clue I came across is an error that the cleanup utility spits out, which makes it sound like a duplicate key was put into the server dictionary: 
```
C:\Users\Administrator>unity-cache-server-cleanup
Cache path is H:/unity-cache/cache_ram
Error: Duplicate key for property fileId: 352db1b773d4b474b980de13593fc73d-aab3c2afb47c9381dc29b4de66a9a3c5-i
    at UniqueIndex.set (C:\Users\Administrator\AppData\Roaming\npm\node_modules\unity-cache-server\node_modules\lokijs\src\lokijs.js:7246:17)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\unity-cache-server\node_modules\lokijs\src\lokijs.js:5439:15
    at Array.forEach (<anonymous>)
    at Collection.ensureUniqueIndex (C:\Users\Administrator\AppData\Roaming\npm\node_modules\unity-cache-server\node_modules\lokijs\src\lokijs.js:5438:17)
    at Loki.loadJSONObject (C:\Users\Administrator\AppData\Roaming\npm\node_modules\unity-cache-server\node_modules\lokijs\src\lokijs.js:1728:22)
    at Loki.loadJSON (C:\Users\Administrator\AppData\Roaming\npm\node_modules\unity-cache-server\node_modules\lokijs\src\lokijs.js:1626:12)
    at loadDatabaseCallback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\unity-cache-server\node_modules\lokijs\src\lokijs.js:2515:20)
    at readFileCallback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\unity-cache-server\node_modules\lokijs\src\lokijs.js:2327:15)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

I have a forum post on this here with a bit more detail: https://forum.unity.com/threads/cache-server-6-3-0-exits-silently-when-trying-to-run-from-previous-cache_ram-data.689830/

Thanks!

**Comment by stephen-palmer** [comment]
The cleanup script doesn't do anything for the RAM cache, since it's a fixed-size, LRU cache already. All it's doing is loading the database for the cache index, which is the same thing that happens when you startup the cache. I guess the in former case, it's just not printing this error (it should).

It's not immediately obvious how the database can get into this state, as (presumably) transactions are atomic and the field is indexed.

can you send me the `cache.db` file in your cache directory, after it's ended up in this state?

**Comment by LaserCannon** [comment]
Interesting that the cleanup tool isn't complaining about that then. Or maybe it's just not getting past parsing the cache.db file?

Fortunately I kept a cache.db file from when it crashed before, and I just emailed that to you. Hope it helps.
