### ISSUE TITLE
Bad Client protocol version problem

### ISSUE THREAD

**Issue by doodoori2** [Unity-Technologies/unity-cache-server#180]
```
Error: Unrecognized command, aborting!: CH
    at ClientStreamProcessor._sendCommands (/usr/lib/node_modules/unity-cache-server/lib/server/client_stream_processor.js:163:42)
    at ClientStreamProcessor._transform (/usr/lib/node_modules/unity-cache-server/lib/server/client_stream_processor.js:66:25)
    at ClientStreamProcessor.Transform._read (internal/streams/transform.js:205:10)
    at ClientStreamProcessor.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at ClientStreamProcessor.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:726:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
Bad Client protocol version
```

Install nodejs 14 through the apt-get. 
and I installed unity cache server with npm.
my new cache server is not working with the error message.

so I opened the client_stream_processor.js.

version 6.4.0
https://github.com/Unity-Technologies/unity-cache-server/blob/release/v6.4.0/lib/server/client_stream_processor.js#L146

master branch
https://github.com/Unity-Technologies/unity-cache-server/blob/master/lib/server/client_stream_processor.js#L146

There is a switch code that read cmd[0] to handle three cases 'g','p' and 't'.
so I check variable cmd, the value is 'CH' .
I don't know what the value of CH means. 

What should I do? here is my version information.

```
Unity 2020.3.8 LTS

$ unity-cache-server -V
6.4.0

$ node --version
v14.17.4

$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

$ uname -a
Linux ip-172-31-12-124 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by doodoori2** [comment]
Same with latest installation as github source
npm install github:Unity-Technologies/unity-cache-server -g

**Comment by doodoori2** [comment]
I had to install an accelerator, not a unity cache server.
