### ISSUE TITLE
Can't start Cache-Server 6.0

### ISSUE THREAD

**Issue by matheus-cardoso-movile** [Unity-Technologies/unity-cache-server#21]
Hi, I'm following the tutorial of the new Cache server on a Mac Mini and I'm getting the following error every time I try to start the server:

> /usr/local/lib/node_modules/unity-cache-server/main.js:6
> const { Server } = require('./lib');
>       ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3

I installed using the default NPM procedure.

**Comment by matheus-cardoso-movile** [comment]
Nevermind, if you got this error, maybe your Node.js or NPM are out of date. Make sure to get the right version before installing the unity-cache-server.
