### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by marnel-estrada** [Unity-Technologies/unity-cache-server#22]
Got this error:
C:\Users\Marnel\AppData\Roaming\npm\node_modules\unity-cache-server\main.js:99
    let mirrors = program.mirror.map(async m => {
                                     ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

This was the command I used:
unity-cache-server -P E:\InstalledPrograms\UnityCacheServer6\Cache -w 1

Am I missing something?

**Comment by quentinleguennec** [comment]
Same here.
I downgraded to unity-cache-server@5.5.0 and it works fine.

**Comment by stephen-palmer** [comment]
Are you running with Node v8?

**Comment by quentinleguennec** [comment]
No, v6.11.0

**Comment by stephen-palmer** [comment]
v8 is required - latest LTS release (v8.10)
