### ISSUE TITLE
Unity Cache Server Crash: RangeError [ERR_INVALID_ASYNC_ID]

### ISSUE THREAD

**Issue by timezombi** [Unity-Technologies/unity-cache-server#40]
Our Unity Cache Server instance has crashed a few times when running continuously for several days. As far as I can tell, the crash seems to occur shortly after very large requests (50k+ files), but I can't find a real pattern.

The first crash was when `unity-cache-server-cleanup` was running in daemon mode. The second time was when `unity-cache-server-cleanup` was running as a cronjob every 24 hours. If you think that this might be a contributing factor, I can disable the unity-cache-server-cleanup script entirely until the issue is fixed.

Attached is the end of the last crash that occurred with the default log verbosity. This is running in our production environment, so I am a little hesitant to run this with maximum log verbosity, however I will do so if it helps resolve this problem faster.

[UnityCrash2.txt](https://github.com/Unity-Technologies/unity-cache-server/files/2024224/UnityCrash2.txt)

Note the error:

> RangeError [ERR_INVALID_ASYNC_ID]: Invalid asyncId value: -2147483646
    at validateAsyncId (internal/async_hooks.js:116:16)
    at emitBeforeScript (internal/async_hooks.js:318:3)
    at process._tickCallback (internal/process/next_tick.js:97:9)

Sorry that I cannot give additional details. The error message and the time frame that this crash operates on makes it difficult to troubleshoot this.

**Comment by timezombi** [comment]
Additional system information:
Ubuntu 16.04 LTS, kernel 4.13.0-41
npm 5.8.0
node 9.10.1
Unity Cache Server 6.0.2

**Comment by timezombi** [comment]
I don't usually like doing this, but since this is crashing often enough, I'm going to run the script in a while loop so that it automatically recovers from crashes (e.g. https://askubuntu.com/questions/572820/re-run-an-application-script-when-it-crashes/572823 ). Do you know if the ERR_INVALID_ASYNC_ID error is going to corrupt our cache or is this generally a harmless error? Also, does Unity Cache Server ever return 0 as its exit status when a crash occurs?

**Comment by stephen-palmer** [comment]
Thanks for reporting this - I don't believe this has been seen internally or elsewhere yet.

One thing that sticks out to me, is that you are running Node 9.10.1 .. we have not tested with Node 9 at all. I recommend switching to the LTS release (8.11) and see if that makes a difference.

Otherwise, I don't think this should affect cache integrity. The exit status on a hard crash would be set by Node, which is likely 1 but I'm not entirely sure.

**Comment by timezombi** [comment]
Whoa, nice catch! I switched to node 8.11 just now. Will update if there are further problems.

Thank you for your prompt response!
