### ISSUE TITLE
Release v6.2.0 Fails To Start

### ISSUE THREAD

**Issue by AaronZurawski** [Unity-Technologies/unity-cache-server#96]
This issue does not occur in 6.0 or in 6.2.1, but is present in the 6.2.0 release on npm.

## Environment
**Version**: 6.2.0
**OS**: Ubuntu 18.04
**Node**: v8.10.0

## Repro:

1. Install with `npm install unity-cache-server@6.2.0 -g`
2. Run using `unity-cache-server`

## Result:

```root@e7ca08d49da1:/# unity-cache-server
module.js:549
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/unity-cache-server/main.js:5:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)```

**Comment by stephen-palmer** [comment]
This is fixed in the latest release (6.2.3)
